version: '3.8'

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}_app
    build:
      context: php
    depends_on:
      - database
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:1.19-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
  database:
    container_name: ${COMPOSE_PROJECT_NAME}_database
    image: mariadb:10.5.12
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
    volumes:
      - ./../data/sql:/docker-entrypoint-initdb.d
